services:
  db:
    image: mysql:8.0
    container_name: url_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: urlDB
      MYSQL_USER: bahaa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: